#ifndef _RS_COMMAND_H_
#define _RS_COMMAND_H_

#include <corecrt.h>

typedef enum {
  AT_INT,
  AT_COLOR,
  AT_FLOAT,
  AT_STRING,
  AT_VECTOR2,
  AT_RECTANGLE,
} RSArgType;


// TODO: Add funcs that return values
// TODO: Add funcs that ref images/textures/fonts
// TODO: Add funcs that have array parms

typedef enum {
  // R_CORE
  FC_SET_WINDOW_TITLE,
  FC_SET_WINDOW_POSITION,
  FC_SET_WINDOW_SIZE,
  FC_CLEAR_BACKGROUND,
  FC_TAKE_SCREENSHOT,

  // R_SHAPES
  FC_DRAW_PIXEL,
  FC_DRAW_PIXEL_V,
  FC_DRAW_LINE,
  FC_DRAW_LINE_V,
  FC_DRAW_LINE_EX,
  FC_DRAW_LINE_BEZIER,
  FC_DRAW_LINE_DASHED,
  FC_DRAW_CIRCLE,
  FC_DRAW_CIRCLE_V,
  FC_DRAW_CIRCLE_GRADIENT,
  FC_DRAW_CIRCLE_SECTOR,
  FC_DRAW_CIRCLE_SECTOR_LINES,
  FC_DRAW_CIRCLE_LINES,
  FC_DRAW_CIRCLE_LINES_V,
  FC_DRAW_ELLIPSE,
  FC_DRAW_ELLIPSE_V,
  FC_DRAW_ELLIPSE_LINES,
  FC_DRAW_ELLIPSE_LINES_V,
  FC_DRAW_RING,
  FC_DRAW_RING_LINES,
  FC_DRAW_RECTANGLE,
  FC_DRAW_RECTANGLE_V,
  FC_DRAW_RECTANGLE_REC,
  FC_DRAW_RECTANGLE_PRO,
  FC_DRAW_RECTANGLE_GRADIENT_V,
  FC_DRAW_RECTANGLE_GRADIENT_H,
  FC_DRAW_RECTANGLE_GRADIENT_EX,
  FC_DRAW_RECTANGLE_LINES,
  FC_DRAW_RECTANGLE_LINES_EX,
  FC_DRAW_RECTANGLE_ROUNDED,
  FC_DRAW_RECTANGLE_ROUNDED_LINES,
  FC_DRAW_RECTANGLE_ROUNDED_LINES_EX,
  FC_DRAW_TRIANGLE,
  FC_DRAW_TRIANGLE_LINES,
  FC_DRAW_POLY,
  FC_DRAW_POLY_LINES,
  FC_DRAW_POLY_LINES_EX,
  FC_DRAW_SPLINE_SEGMENT_LINEAR,
  FC_DRAW_SPLINE_SEGMENT_BASIS,
  FC_DRAW_SPLINE_SEGMENT_CATMULL_ROM,
  FC_DRAW_SPLINE_SEGMENT_BEZIER_QUADRATIC,
  FC_DRAW_SPLINE_SEGMENT_BEZIER_CUBIC,

  // R_TEXTURES
  FC_GEN_IMAGE_COLOR,

  // R_TEXT
  FC_DRAW_FPS,
  FC_DRAW_TEXT,
  FC_SET_TEXT_LINE_SPACING,

  // R_MODELS
  
  // R_AUDIO
} FuncCode;

#define RS_NUM_FUNCS 51

// A single instruction for the target machine
typedef struct {
  FuncCode func;
  int argc;
  char **argv;
} RSCommand;

void RSCommandFree(RSCommand *cmd);

char *RSCommandPackage(RSCommand *cmd);

errno_t RSCommandInit(RSCommand *cmd, int argc, FuncCode func);

#endif
