#ifndef _RS_COMMAND_H_
#define _RS_COMMAND_H_

#include <corecrt.h>

typedef enum {
  AT_INT,
  AT_COLOR,
  AT_FLOAT,
  AT_STRING,
  AT_VECTOR2,
  AT_RECTANGLE,
  AT_IMAGE,
  AT_TEXTURE,
} RSArgType;


// TODO: Add funcs that return values
// TODO: Add funcs that ref fonts
// TODO: Add funcs that have array parms

typedef enum {
  // R_CORE
  FC_SET_WINDOW_TITLE,
  FC_SET_WINDOW_POSITION,
  FC_SET_WINDOW_SIZE,
  FC_CLEAR_BACKGROUND,
  FC_TAKE_SCREENSHOT,

  // R_SHAPES
  FC_DRAW_PIXEL,
  FC_DRAW_PIXEL_V,
  FC_DRAW_LINE,
  FC_DRAW_LINE_V,
  FC_DRAW_LINE_EX,
  FC_DRAW_LINE_BEZIER,
  FC_DRAW_LINE_DASHED,
  FC_DRAW_CIRCLE,
  FC_DRAW_CIRCLE_V,
  FC_DRAW_CIRCLE_GRADIENT,
  FC_DRAW_CIRCLE_SECTOR,
  FC_DRAW_CIRCLE_SECTOR_LINES,
  FC_DRAW_CIRCLE_LINES,
  FC_DRAW_CIRCLE_LINES_V,
  FC_DRAW_ELLIPSE,
  FC_DRAW_ELLIPSE_V,
  FC_DRAW_ELLIPSE_LINES,
  FC_DRAW_ELLIPSE_LINES_V,
  FC_DRAW_RING,
  FC_DRAW_RING_LINES,
  FC_DRAW_RECTANGLE,
  FC_DRAW_RECTANGLE_V,
  FC_DRAW_RECTANGLE_REC,
  FC_DRAW_RECTANGLE_PRO,
  FC_DRAW_RECTANGLE_GRADIENT_V,
  FC_DRAW_RECTANGLE_GRADIENT_H,
  FC_DRAW_RECTANGLE_GRADIENT_EX,
  FC_DRAW_RECTANGLE_LINES,
  FC_DRAW_RECTANGLE_LINES_EX,
  FC_DRAW_RECTANGLE_ROUNDED,
  FC_DRAW_RECTANGLE_ROUNDED_LINES,
  FC_DRAW_RECTANGLE_ROUNDED_LINES_EX,
  FC_DRAW_TRIANGLE,
  FC_DRAW_TRIANGLE_LINES,
  FC_DRAW_POLY,
  FC_DRAW_POLY_LINES,
  FC_DRAW_POLY_LINES_EX,
  FC_DRAW_SPLINE_SEGMENT_LINEAR,
  FC_DRAW_SPLINE_SEGMENT_BASIS,
  FC_DRAW_SPLINE_SEGMENT_CATMULL_ROM,
  FC_DRAW_SPLINE_SEGMENT_BEZIER_QUADRATIC,
  FC_DRAW_SPLINE_SEGMENT_BEZIER_CUBIC,

  // R_TEXTURES
  FC_LOAD_IMAGE,
  FC_LOAD_IMAGE_RAW,
  FC_LOAD_IMAGE_FROM_TEXTURE,
  FC_LOAD_IMAGE_FROM_SCREEN,
  FC_UNLOAD_IMAGE,
  FC_GEN_IMAGE_COLOR,
  FC_GEN_IMAGE_GRADIENT_LINEAR,
  FC_GEN_IMAGE_GRADIENT_RADIAL,
  FC_GEN_IMAGE_GRADIENT_SQUARE,
  FC_GEN_IMAGE_CHECKED,
  FC_GEN_IMAGE_WHITE_NOISE,
  FC_GEN_IMAGE_PERLIN_NOISE,
  FC_GEN_IMAGE_CELLULAR,
  FC_GEN_IMAGE_TEXT,
  FC_IMAGE_COPY,
  FC_IMAGE_FROM_IMAGE,
  FC_IMAGE_FROM_CHANNEL,
  FC_IMAGE_TEXT,
  FC_IMAGE_FORMAT,
  FC_IMAGE_TO_POT,
  FC_IMAGE_CROP,
  FC_IMAGE_ALPHA_CROP,
  FC_IMAGE_ALPHA_CLEAR,
  FC_IMAGE_ALPHA_MASK,
  FC_IMAGE_ALPHA_PREMULTIPLY,
  FC_IMAGE_BLUR_GAUSSIAN,
  FC_IMAGE_RESIZE,
  FC_IMAGE_RESIZE_NN,
  FC_IMAGE_RESIZE_CANVAS,
  FC_IMAGE_MIPMAPS,
  FC_IMAGE_DITHER,
  FC_IMAGE_FLIP_VERTICAL,
  FC_IMAGE_FLIP_HORIZONTAL,
  FC_IMAGE_ROTATE,
  FC_IMAGE_ROTATE_CW,
  FC_IMAGE_ROTATE_CCW,
  FC_IMAGE_COLOR_TINT,
  FC_IMAGE_COLOR_INVERT,
  FC_IMAGE_COLOR_GRAYSCALE,
  FC_IMAGE_COLOR_CONTRAST,
  FC_IMAGE_COLOR_BRIGHTNESS,
  FC_IMAGE_COLOR_REPLACE,
  FC_IMAGE_CLEAR_BACKGROUND,
  FC_IMAGE_DRAW_PIXEL,
  FC_IMAGE_DRAW_PIXEL_V,
  FC_IMAGE_DRAW_LINE,
  FC_IMAGE_DRAW_LINE_V,
  FC_IMAGE_DRAW_LINE_EX,
  FC_IMAGE_DRAW_CIRCLE,
  FC_IMAGE_DRAW_CIRCLE_V,
  FC_IMAGE_DRAW_CIRCLE_LINES,
  FC_IMAGE_DRAW_CIRCLE_LINES_V,
  FC_IMAGE_DRAW_RECTANGLE,
  FC_IMAGE_DRAW_RECTANGLE_V,
  FC_IMAGE_DRAW_RECTANGLE_REC,
  FC_IMAGE_DRAW_RECTANGLE_LINES,
  FC_IMAGE_DRAW_TRIANGLE,
  FC_IMAGE_DRAW_TRIANGLE_EX,
  FC_IMAGE_DRAW_TRIANGLE_LINES,
  FC_IMAGE_DRAW,
  FC_IMAGE_DRAW_TEXT,
  FC_LOAD_TEXTURE,
  FC_LOAD_TEXTURE_FROM_IMAGE,
  FC_UNLOAD_TEXTURE,
  FC_GEN_TEXTURE_MIPMAPS,
  FC_SET_TEXTURE_FILTER,
  FC_SET_TEXTURE_WRAP,
  FC_DRAW_TEXTURE,
  FC_DRAW_TEXTURE_V,
  FC_DRAW_TEXTURE_EX,
  FC_DRAW_TEXTURE_REC,
  FC_DRAW_TEXTURE_PRO,

  // R_TEXT
  FC_DRAW_FPS,
  FC_DRAW_TEXT,
  FC_SET_TEXT_LINE_SPACING,

  // R_MODELS
  
  // R_AUDIO
} FuncCode;

#define RS_NUM_FUNCS 122

// A single instruction for the target machine
typedef struct {
  FuncCode func;
  int argc;
  char **argv;
} RSCommand;

void RSCommandFree(RSCommand *cmd);

char *RSCommandPackage(RSCommand *cmd);

errno_t RSCommandInit(RSCommand *cmd, int argc, FuncCode func);

errno_t RSCommandPopulate(RSCommand *cmd, int argc, void **argv, RSArgType *argt);

#endif
