#include <memory.h>
#include <stdio.h>

#include "RSScreenCommands.h"
#include "RSCommand.h"
#include "RSScreen.h"

RSArgType funcArgTypes[RS_NUM_FUNCS][10] = {
  // R_CORE
  {AT_STRING}, // FC_SET_WINDOW_TITLE
  {AT_INT, AT_INT}, // FC_SET_WINDOW_POSITION
  {AT_INT, AT_INT}, // FC_SET_WINDOW_SIZE
  {AT_COLOR}, // FC_CLEAR_BACKGROUND
  {AT_STRING}, // FC_TAKE_SCREENSHOT
  
  // R_SHAPES
  {AT_INT, AT_INT, AT_COLOR}, // FC_DRAW_PIXEL
  {AT_VECTOR2, AT_COLOR}, // FC_DRAW_PIXEL_V
  {AT_INT, AT_INT, AT_INT, AT_INT, AT_COLOR}, // FC_DRAW_LINE
  {AT_VECTOR2, AT_VECTOR2, AT_COLOR}, // FC_DRAW_LINE_V
  {AT_VECTOR2, AT_VECTOR2, AT_FLOAT, AT_COLOR}, // FC_DRAW_LINE_EX
  {AT_VECTOR2, AT_VECTOR2, AT_FLOAT, AT_COLOR}, // FC_DRAW_LINE_BEZIER
  {AT_VECTOR2, AT_VECTOR2, AT_INT, AT_INT, AT_COLOR}, // DC_DRAW_LINE_DASHED
  {AT_INT, AT_INT, AT_FLOAT, AT_COLOR}, // FC_DRAW_CIRCLE
  {AT_VECTOR2, AT_FLOAT, AT_COLOR}, // FC_DRAW_CIRCLE_V
  {AT_VECTOR2, AT_FLOAT, AT_COLOR}, // FC_DRAW_CIRCLE_GRADIENT
  {AT_VECTOR2, AT_FLOAT, AT_FLOAT, AT_FLOAT, AT_INT, AT_COLOR}, // FC_DRAW_CIRCLE_SECTOR
  {AT_VECTOR2, AT_FLOAT, AT_FLOAT, AT_FLOAT, AT_INT, AT_COLOR}, // FC_DRAW_CIRCLE_SECTOR_LINES
  {AT_INT, AT_INT, AT_FLOAT, AT_COLOR}, // FC_DRAW_CIRCLE_LINES
  {AT_VECTOR2, AT_FLOAT, AT_COLOR}, // FC_DRAW_CIRCLE_LINES_V
  {AT_INT, AT_INT, AT_FLOAT, AT_FLOAT, AT_COLOR}, // FC_DRAW_ELLIPSE
  {AT_VECTOR2, AT_FLOAT, AT_FLOAT, AT_COLOR}, // FC_DRAW_ELLIPSE_V
  {AT_INT, AT_INT, AT_FLOAT, AT_FLOAT, AT_COLOR}, // FC_DRAW_ELLIPSE_LINES
  {AT_VECTOR2, AT_FLOAT, AT_FLOAT, AT_COLOR}, // FC_DRAW_ELLIPSE_LINES_V
  {AT_VECTOR2, AT_FLOAT, AT_FLOAT, AT_FLOAT, AT_FLOAT, AT_INT, AT_COLOR}, // FC_DRAW_RING
  {AT_VECTOR2, AT_FLOAT, AT_FLOAT, AT_FLOAT, AT_FLOAT, AT_INT, AT_COLOR}, // FC_DRAW_RING_LINES
  {AT_INT, AT_INT, AT_INT, AT_INT, AT_COLOR}, // FC_DRAW_RECTANGLE
  {AT_VECTOR2, AT_VECTOR2, AT_COLOR}, // FC_DRAW_RECTANGLE_V
  {AT_RECTANGLE, AT_COLOR}, // FC_DRAW_RECTANGLE_REC
  {AT_RECTANGLE, AT_VECTOR2, AT_FLOAT, AT_COLOR}, // FC_DRAW_RECTANGLE_PRO
  {AT_INT, AT_INT, AT_INT, AT_INT, AT_COLOR, AT_COLOR}, // FC_DRAW_RECTANGLE_GRADIENT_V
  {AT_INT, AT_INT, AT_INT, AT_INT, AT_COLOR, AT_COLOR}, // FC_DRAW_RECTANGLE_GRADIENT_H
  {AT_RECTANGLE, AT_COLOR, AT_COLOR, AT_COLOR, AT_COLOR}, // FC_DRAW_RECTANGLE_GRADIENT_EX
  {AT_INT, AT_INT, AT_INT, AT_INT, AT_COLOR}, // FC_DRAW_RECTANGLE_LINES
  {AT_RECTANGLE, AT_FLOAT, AT_COLOR}, // FC_DRAW_RECTANGLE_LINES_EX
  {AT_RECTANGLE, AT_FLOAT, AT_INT, AT_COLOR}, // FC_DRAW_RECTANGLE_ROUNDED
  {AT_RECTANGLE, AT_FLOAT, AT_INT, AT_COLOR}, // FC_DRAW_RECTANGLE_ROUNDED_LINES
  {AT_RECTANGLE, AT_FLOAT, AT_INT, AT_FLOAT, AT_COLOR}, // FC_DRAW_RECTANGLE_ROUNDED_LINES_EX
  {AT_VECTOR2, AT_VECTOR2, AT_VECTOR2, AT_COLOR}, // FC_DRAW_TRIANGLE
  {AT_VECTOR2, AT_VECTOR2, AT_VECTOR2, AT_COLOR}, // FC_DRAW_TRIANGLE_LINES
  {AT_VECTOR2, AT_INT, AT_FLOAT, AT_FLOAT, AT_COLOR}, // FC_DRAW_POLY
  {AT_VECTOR2, AT_INT, AT_FLOAT, AT_FLOAT, AT_COLOR}, // FC_DRAW_POLY_LINES
  {AT_VECTOR2, AT_INT, AT_FLOAT, AT_FLOAT, AT_FLOAT, AT_COLOR}, // FC_DRAW_POLY_LINES_EX
  {AT_VECTOR2, AT_VECTOR2, AT_FLOAT, AT_COLOR}, // FC_DRAW_SPLINE_SEGMENT_LINEAR
  {AT_VECTOR2, AT_VECTOR2, AT_VECTOR2, AT_VECTOR2, AT_FLOAT, AT_COLOR}, // FC_DRAW_SPLINE_SEGMENT_BASIS
  {AT_VECTOR2, AT_VECTOR2, AT_VECTOR2, AT_VECTOR2, AT_FLOAT, AT_COLOR}, // FC_DRAW_SPLINE_SEGMENT_CATMULL_ROM
  {AT_VECTOR2, AT_VECTOR2, AT_VECTOR2, AT_FLOAT, AT_COLOR}, // FC_DRAW_SPLINE_SEGMENT_BEZIER_QUADRATIC
  {AT_VECTOR2, AT_VECTOR2, AT_VECTOR2, AT_VECTOR2, AT_FLOAT, AT_COLOR}, // FC_DRAW_SPLINE_SEGMENT_BEZIER_CUBIC

  // R_TEXTURES
  {AT_STRING}, // FC_LOAD_IMAGE
  {AT_STRING, AT_INT, AT_INT, AT_INT, AT_INT}, // FC_LOAD_IMAGE_RAW
  {AT_TEXTURE}, // FC_LOAD_IMAGE_FROM_TEXTURE
  {}, // FC_LOAD_IMAGE_FROM_SCREEN
  {AT_IMAGE}, // FC_UNLOAD_IMAGE

  {AT_INT, AT_INT, AT_COLOR}, // FC_GEN_IMAGE_COLOR
  {AT_INT, AT_INT, AT_INT, AT_COLOR, AT_COLOR}, // FC_GEN_IMAGE_GRADIENT_LINEAR
  {AT_INT, AT_INT, AT_FLOAT, AT_COLOR, AT_COLOR}, // FC_GEN_IMAGE_GRADIENT_RADIAL
  {AT_INT, AT_INT, AT_FLOAT, AT_COLOR, AT_COLOR}, // FC_GEN_IMAGE_GRADIENT_SQUARE
  {AT_INT, AT_INT, AT_INT, AT_INT, AT_COLOR, AT_COLOR}, // FC_GEN_IMAGE_CHECKED
  {AT_INT, AT_INT, AT_FLOAT}, // FC_GEN_IMAGE_WHITE_NOISE
  {AT_INT, AT_INT, AT_INT, AT_INT, AT_FLOAT}, // FC_GEN_IMAGE_PERLIN_NOISE
  {AT_INT, AT_INT, AT_INT}, // FC_GEN_IMAGE_CELLULAR
  {AT_INT, AT_INT, AT_STRING}, // FC_GEN_IMAGE_TEXT
  
  {AT_IMAGE}, // FC_IMAGE_COPY
  {AT_IMAGE, AT_RECTANGLE}, // FC_IMAGE_FROM_IMAGE
  {AT_IMAGE, AT_INT}, // FC_IMAGE_FROM_CHANNEL
  {AT_STRING, AT_INT, AT_COLOR}, // FC_IMAGE_TEXT
  {AT_IMAGE, AT_INT}, // FC_IMAGE_FORMAT
  {AT_IMAGE, AT_COLOR}, // FC_IMAGE_TO_POT
  {AT_IMAGE, AT_RECTANGLE}, // FC_IMAGE_CROP
  {AT_IMAGE, AT_FLOAT}, // FC_IMAGE_ALPHA_CROP
  {AT_IMAGE, AT_COLOR, AT_FLOAT}, // FC_IMAGE_ALPHA_CLEAR
  {AT_IMAGE, AT_IMAGE}, // FC_IMAGE_ALPHA_MASK
  {AT_IMAGE}, // FC_IMAGE_ALPHA_PREMULTIPLY
  {AT_IMAGE, AT_INT}, // FC_IMAGE_BLUR_GAUSSIAN
  {AT_IMAGE, AT_INT, AT_INT}, // FC_IMAGE_RESIZE
  {AT_IMAGE, AT_INT, AT_INT}, // FC_IMAGE_RESIZE_NN
  {AT_IMAGE, AT_INT, AT_INT, AT_INT, AT_INT, AT_COLOR}, // FC_IMAGE_RESIZE_CANVAS
  {AT_IMAGE}, // FC_IMAGE_MIPMAPS
  {AT_IMAGE, AT_INT, AT_INT, AT_INT}, // FC_IMAGE_DITHER
  {AT_IMAGE}, // FC_IMAGE_FLIP_VERTICAL
  {AT_IMAGE}, // FC_IMAGE_FLIP_HORIZONTAL
  {AT_IMAGE, AT_INT}, // FC_IMAGE_ROTATE
  {AT_IMAGE}, // FC_IMAGE_ROTATE_CW
  {AT_IMAGE}, // FC_IMAGE_ROTATE_CCW
  {AT_IMAGE, AT_COLOR}, // FC_IMAGE_COLOR_TINT
  {AT_IMAGE}, // FC_IMAGE_COLOR_INVERT
  {AT_IMAGE}, // FC_IMAGE_COLOR_GRAYSCALE
  {AT_IMAGE, AT_FLOAT}, // FC_IMAGE_COLOR_CONTRAST
  {AT_IMAGE, AT_INT}, // FC_IMAGE_COLOR_BRIGHTNESS
  {AT_IMAGE, AT_COLOR, AT_COLOR}, // FC_IMAGE_COLOR_REPLACE
  
  {AT_IMAGE, AT_COLOR}, // FC_IMAGE_CLEAR_BACKGROUND
  {AT_IMAGE, AT_INT, AT_INT, AT_COLOR}, // FC_IMAGE_DRAW_PIXEL
  {AT_IMAGE, AT_VECTOR2, AT_COLOR}, // FC_IMAGE_DRAW_PIXEL_V
  {AT_IMAGE, AT_INT, AT_INT, AT_INT, AT_INT, AT_COLOR}, // FC_IMAGE_DRAW_LINE
  {AT_IMAGE, AT_VECTOR2, AT_VECTOR2, AT_COLOR}, // FC_IMAGE_DRAW_LINE_V
  {AT_IMAGE, AT_VECTOR2, AT_VECTOR2, AT_INT, AT_COLOR}, // FC_IMAGE_DRAW_LINE_EX
  {AT_IMAGE, AT_INT, AT_INT, AT_INT, AT_COLOR}, // FC_IMAGE_DRAW_CIRCLE
  {AT_IMAGE, AT_VECTOR2, AT_INT, AT_COLOR}, // FC_IMAGE_DRAW_CIRCLE_V
  {AT_IMAGE, AT_INT, AT_INT, AT_INT, AT_COLOR}, // FC_IMAGE_DRAW_CIRCLE_LINES
  {AT_IMAGE, AT_VECTOR2, AT_INT, AT_COLOR}, // FC_IMAGE_DRAW_CIRCLE_LINES_V
  {AT_IMAGE, AT_INT, AT_INT, AT_INT, AT_INT, AT_COLOR}, // FC_IMAGE_DRAW_RECTANGLE
  {AT_IMAGE, AT_VECTOR2, AT_VECTOR2, AT_COLOR}, // FC_IMAGE_DRAW_RECTANGLE_V
  {AT_IMAGE, AT_RECTANGLE, AT_COLOR}, // FC_IMAGE_DRAW_RECTANGLE_REC
  {AT_IMAGE, AT_RECTANGLE, AT_INT, AT_COLOR}, // FC_IMAGE_DRAW_RECTANGLE_LINES
  {AT_IMAGE, AT_VECTOR2, AT_VECTOR2, AT_VECTOR2, AT_COLOR}, // FC_IMAGE_DRAW_TRIANGLE
  {AT_IMAGE, AT_VECTOR2, AT_VECTOR2, AT_VECTOR2, AT_COLOR, AT_COLOR, AT_COLOR}, // FC_IMAGE_DRAW_TRIANGLE_EX
  {AT_IMAGE, AT_VECTOR2, AT_VECTOR2, AT_VECTOR2, AT_COLOR}, // FC_IMAGE_DRAW_TRIANGLE_LINES
  {AT_IMAGE, AT_IMAGE, AT_RECTANGLE, AT_RECTANGLE, AT_COLOR}, // FC_IMAGE_DRAW
  {AT_IMAGE, AT_STRING, AT_INT, AT_INT, AT_INT, AT_COLOR}, // FC_IMAGE_DRAW_TEXT
  
  {AT_STRING}, // FC_LOAD_TEXTURE
  {AT_IMAGE}, // FC_LOAD_TEXTURE_FROM_IMAGE
  {AT_TEXTURE}, // FC_UNLOAD_TEXTURE
  
  {AT_TEXTURE}, // FC_GEN_TEXTURE_MIPMAPS
  {AT_TEXTURE, AT_INT}, // FC_SET_TEXTURE_FILTER
  {AT_TEXTURE, AT_INT}, // FC_SET_TEXTURE_WRAP
  
  {AT_TEXTURE, AT_INT, AT_INT, AT_COLOR}, // FC_DRAW_TEXTURE
  {AT_TEXTURE, AT_VECTOR2, AT_COLOR}, // FC_DRAW_TEXTURE_V
  {AT_TEXTURE, AT_VECTOR2, AT_FLOAT, AT_FLOAT, AT_COLOR}, // FC_DRAW_TEXTURE_EX
  {AT_TEXTURE, AT_RECTANGLE, AT_VECTOR2, AT_COLOR}, // FC_DRAW_TEXTURE_REC
  {AT_TEXTURE, AT_RECTANGLE, AT_RECTANGLE, AT_VECTOR2, AT_FLOAT, AT_COLOR}, // FC_DRAW_TEXTURE_PRO

  // R_TEXT
  {AT_INT, AT_INT}, // FC_DRAW_FPS
  {AT_STRING, AT_INT, AT_INT, AT_INT, AT_COLOR}, // FC_DRAW_TEXT
  {AT_INT}, // FC_SET_TEXT_LINE_SPACING
};

int funcArgc[RS_NUM_FUNCS] = {
  // R_CORE
  1, // FC_SET_WINDOW_TITLE
  2, // FC_SET_WINDOW_POSITION
  2, // FC_SET_WINDOW_SIZE
  1, // FC_CLEAR_BACKGROUND
  1, // FC_TAKE_SCREENSHOT
  
  // R_SHAPES
  3, // FC_DRAW_PIXEL
  2, // FC_DRAW_PIXEL_V
  5, // FC_DRAW_LINE
  3, // FC_DRAW_LINE_V
  4, // FC_DRAW_LINE_EX
  4, // FC_DRAW_LINE_BEZIER
  5, // DC_DRAW_LINE_DASHED
  4, // FC_DRAW_CIRCLE
  3, // FC_DRAW_CIRCLE_V
  4, // FC_DRAW_CIRCLE_GRADIENT
  6, // FC_DRAW_CIRCLE_SECTOR
  6, // FC_DRAW_CIRCLE_SECTOR_LINES
  4, // FC_DRAW_CIRCLE_LINES
  3, // FC_DRAW_CIRCLE_LINES_V
  5, // FC_DRAW_ELLIPSE
  4, // FC_DRAW_ELLIPSE_V
  5, // FC_DRAW_ELLIPSE_LINES
  4, // FC_DRAW_ELLIPSE_LINES_V
  7, // FC_DRAW_RING
  7, // FC_DRAW_RING_LINES
  5, // FC_DRAW_RECTANGLE
  3, // FC_DRAW_RECTANGLE_V
  2, // FC_DRAW_RECTANGLE_REC
  4, // FC_DRAW_RECTANGLE_PRO
  6, // FC_DRAW_RECTANGLE_GRADIENT_V
  6, // FC_DRAW_RECTANGLE_GRADIENT_H
  5, // FC_DRAW_RECTANGLE_GRADIENT_EX
  5, // FC_DRAW_RECTANGLE_LINES
  3, // FC_DRAW_RECTANGLE_LINES_EX
  4, // FC_DRAW_RECTANGLE_ROUNDED
  4, // FC_DRAW_RECTANGLE_ROUNDED_LINES
  5, // FC_DRAW_RECTANGLE_ROUNDED_LINES_EX
  4, // FC_DRAW_TRIANGLE
  4, // FC_DRAW_TRIANGLE_LINES
  5, // FC_DRAW_POLY
  5, // FC_DRAW_POLY_LINES
  6, // FC_DRAW_POLY_LINES_EX
  4, // FC_DRAW_SPLINE_SEGMENT_LINEAR
  6, // FC_DRAW_SPLINE_SEGMENT_BASIS
  6, // FC_DRAW_SPLINE_SEGMENT_CATMULL_ROM
  5, // FC_DRAW_SPLINE_SEGMENT_BEZIER_QUADRATIC
  6, // FC_DRAW_SPLINE_SEGMENT_BEZIER_CUBIC

  // R_TEXTURES
  1, // FC_LOAD_IMAGE
  5, // FC_LOAD_IMAGE_RAW
  1, // FC_LOAD_IMAGE_FROM_TEXTURE
  0, // FC_LOAD_IMAGE_FROM_SCREEN
  1, // FC_UNLOAD_IMAGE
  
  3, // FC_GEN_IMAGE_COLOR
  5, // FC_GEN_IMAGE_GRADIENT_LINEAR
  5, // FC_GEN_IMAGE_GRADIENT_RADIAL
  5, // FC_GEN_IMAGE_GRADIENT_SQUARE
  6, // FC_GEN_IMAGE_CHECKED
  3, // FC_GEN_IMAGE_WHITE_NOISE
  5, // FC_GEN_IMAGE_PERLIN_NOISE
  3, // FC_GEN_IMAGE_CELLULAR
  3, // FC_GEN_IMAGE_TEXT
  
  1, // FC_IMAGE_COPY
  2, // FC_IMAGE_FROM_IMAGE
  2, // FC_IMAGE_FROM_CHANNEL
  3, // FC_IMAGE_TEXT
  2, // FC_IMAGE_FORMAT
  2, // FC_IMAGE_TO_POT
  2, // FC_IMAGE_CROP
  2, // FC_IMAGE_ALPHA_CROP
  3, // FC_IMAGE_ALPHA_CLEAR
  2, // FC_IMAGE_ALPHA_MASK
  1, // FC_IMAGE_ALPHA_PREMULTIPLY
  2, // FC_IMAGE_BLUR_GAUSSIAN
  3, // FC_IMAGE_RESIZE
  3, // FC_IMAGE_RESIZE_NN
  6, // FC_IMAGE_RESIZE_CANVAS
  1, // FC_IMAGE_MIPMAPS
  5, // FC_IMAGE_DITHER
  1, // FC_IMAGE_FLIP_VERTICAL
  1, // FC_IMAGE_FLIP_HORIZONTAL
  2, // FC_IMAGE_ROTATE
  1, // FC_IMAGE_ROTATE_CW
  1, // FC_IMAGE_ROTATE_CCW
  2, // FC_IMAGE_COLOR_TINT
  1, // FC_IMAGE_COLOR_INVERT
  1, // FC_IMAGE_COLOR_GRAYSCALE
  2, // FC_IMAGE_COLOR_CONTRAST
  2, // FC_IMAGE_COLOR_BRIGHTNESS
  3, // FC_IMAGE_COLOR_REPLACE
  
  2, // FC_IMAGE_CLEAR_BACKGROUND
  4, // FC_IMAGE_DRAW_PIXEL
  3, // FC_IMAGE_DRAW_PIXEL_V
  6, // FC_IMAGE_DRAW_LINE
  4, // FC_IMAGE_DRAW_LINE_V
  5, // FC_IMAGE_DRAW_LINE_EX
  5, // FC_IMAGE_DRAW_CIRCLE
  4, // FC_IMAGE_DRAW_CIRCLE_V
  5, // FC_IMAGE_DRAW_CIRCLE_LINES
  4, // FC_IMAGE_DRAW_CIRCLE_LINES_V
  6, // FC_IMAGE_DRAW_RECTANGLE
  4, // FC_IMAGE_DRAW_RECTANGLE_V
  3, // FC_IMAGE_DRAW_RECTANGLE_REC
  4, // FC_IMAGE_DRAW_RECTANGLE_LINES
  5, // FC_IMAGE_DRAW_TRIANGLE
  7, // FC_IMAGE_DRAW_TRIANGLE_EX
  5, // FC_IMAGE_DRAW_TRIANGLE_LINES
  5, // FC_IMAGE_DRAW
  6, // FC_IMAGE_DRAW_TEXT
  
  1, // FC_LOAD_TEXTURE
  1, // FC_LOAD_TEXTURE_FROM_IMAGE
  1, // FC_UNLOAD_TEXTURE
  
  1, // FC_GEN_TEXTURE_MIPMAPS
  2, // FC_SET_TEXTURE_FILTER
  2, // FC_SET_TEXTURE_WRAP
  
  4, // FC_DRAW_TEXTURE
  3, // FC_DRAW_TEXTURE_V
  5, // FC_DRAW_TEXTURE_EX
  4, // FC_DRAW_TEXTURE_REC
  6, // FC_DRAW_TEXTURE_PRO

  // R_TEXT
  2, // FC_DRAW_FPS
  5, // FC_DRAW_TEXT
  1, // FC_SET_TEXT_LINE_SPACING
};

RSFuncMetaData RSGetFuncMetadata(FuncCode func) {
  if (func >= RS_NUM_FUNCS) {
    return (RSFuncMetaData){0, NULL};
  }

  return (RSFuncMetaData){funcArgc[func], funcArgTypes[func]};
}

void RSDeployCommand(RSScreen *screen, FuncCode func, void **argv) {
  if (func >= RS_NUM_FUNCS) {
    printf("Invalid func code given\n");
    return;
  }

  RSCommand cmd;

  // Get some info about this func
  const int argc = funcArgc[func];
  RSArgType *argt = funcArgTypes[func];

  if (RSCommandInit(&cmd, argc, func)) {
    printf("Couldn't initialise command\n");
    return;
  }

  errno_t err = RSCommandPopulate(&cmd, argc, argv, argt);
  if (err) {
    printf("Couldn't populate command\n");
    return;
  }

  RSScreenQueuePush(screen, cmd);
}
